### ISSUE TITLE
Setting up a shop page

### ISSUE THREAD

**Issue by ffeel31** [eckmarcommunity/eckmar#107]
Please can anyone help with the procedure on setting up a page called shop that displays all the products of the different vendors and possibly with a filter thanks.

**Comment by ffeel31** [comment]
thanks, i have been able to add the page and even added other functionalities like a wallet system

**Comment by ffeel31** [comment]
no further help needed

**Comment by anprguy** [comment]
Would you be able to advise how you did this for other who may want to do the same?
