### ISSUE TITLE
PGP no found MSG KEY Validator

### ISSUE THREAD

**Issue by c0d3r-devel** [eckmarcommunity/eckmar#113]
hello:

After installing and following the steps I only need to install the BTCGateway part.

But in the first tests when I create the admin account and give it admin permissions, any account that thinks it wants to add the PGP Public Key for validation, the page returns this to me without a message.

I have Ubuntu 20.04
node v10.19.0
npm 6.14.4
php7.2

Please help with this i dont know what is the problem, I have all afternoom try try try and notigh.

Thanks

![imagen](https://github.com/eckmar-community/eckmar/assets/167721804/4ec23901-4a81-4e47-b6ad-a56d20a379f0)

**Comment by Gralien** [comment]
When you add a key. Triple  check the spacing. You may have to manually
adjust the key after pasting it in?

**Comment by c0d3r-devel** [comment]
> When you add a key. Triple check the spacing. You may have to manually adjust the key after pasting it in?

Hello, I have done it in a thousand ways, I have even tried with another generated one, at some point it shows me a PGP message but it doesn't let me decrypt it either, it tells me that it has no data.

You give me those two things or it doesn't give me the message or the PGP message it gives me I can't decrypt it with the PUB KEY that I have entered.

It's a bit strange really.

EDIT:  I generte PGP with RSA metod and found, if it use other metod encriptation no support pgp need RSA i thing
