### ISSUE TITLE
Issue with Release of Funds from Escrow

### ISSUE THREAD

**Issue by thisisforjimmy** [eckmarcommunity/eckmar#23]
Okay so everything is working great but one issue. I have a customer the buys the product. The order is generated including the btc address. The payment is made. The payment is confirmed. So when the customer goes to mark the order as delivered. I get an error (Error happened! Please try again later! ). Not sure what the problem is. Any help would be much appreciated. Thank you.

**Comment by thisisforjimmy** [comment]
Okay so maybe this will help. I was trying out disputes and when I go to resolve I get this error. (Something went wrong, please try again!Invalid Bitcoin address: Sending to: To xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx : 0.00016525 To : 0 . Ive tried several VALID addresses.

**Comment by thisisforjimmy** [comment]
So I somewhat got it going but now the error i get is Something went wrong, please try again!Insufficient funds Sending to:

**Comment by dclipca** [comment]
@thisisforjimmy did you do successful transactions before or this is the first transaction and it spits out this error. Might be associated with the BTC daemon being set up incorrectly.

**Comment by thisisforjimmy** [comment]
Found the problem. It was in the code. Added  subtractfeefrom in the command and it fixed it.

**Comment by linkified** [comment]
can you post the code you added for sendmany on subtract from fee, im looking at the arg and i dont see the command in its self it seems that it does it automatically but you have to add the amount then the address again

**Comment by ffeel31** [comment]
one thing i have noticed on here is this, when guys have issues with code or errors, they come here and if by chance they find the solution and another guy is facing same issues, they don't share.

**Comment by Gralien** [comment]
Alot of the issues people face are already solved in closed issues.  We
shouldn't have to reiterate.
