### ISSUE TITLE
UnexpectedValueException

### ISSUE THREAD

**Issue by c-for-coder** [eckmarcommunity/eckmar#24]
I keep getting this error:
"The stream or file "/var/www/peralta/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied"

![Screenshot (9)](https://user-images.githubusercontent.com/95431339/170874338-4a3c161c-b28b-4a20-9982-b9a62c147d5b.png)

**Comment by dclipca** [comment]
@c-for-coder are you in the process of installing ```eckmar```?

**Comment by c-for-coder** [comment]
> @c-for-coder are you in the process of installing `eckmar`?

yessir Im on, and i fixed the "Unexpected value" Issue, but now i got another one -_-
                     "Undefined Index: name"

![Screenshot (12)](https://user-images.githubusercontent.com/95431339/170882882-15f5d4be-e607-4bbd-a674-05ace709b25f.png)

**Comment by dclipca** [comment]
@c-for-coder what step of the installation instructions are you on? This might be related to not downloading PHP dependencies correctly.

**Comment by c-for-coder** [comment]
> @c-for-coder what step of the installation instructions are you on? This might be related to not downloading PHP dependencies correctly.

OMG..! Youre right, When i tried "sudo apt-get install php7.2-fpm php-mysql" i got some errors so i followed another method to install PHP & Ended up like this so Now im gonna start again. Tysm for clearing my doubt. Ill be back real quick..
