### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '|'

### ISSUE THREAD

**Issue by pwnsociety** [eckmarcommunity/eckmar#25]
in Installation when i put this command line "composer install" i get this error i try it many thing to fix this error nothing works
Error:
```
root@M:/var/www/peralta# composer install
PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /usr/share/php/Composer/IO/BaseIO.php on line 163

Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /usr/share/php/Composer/IO/BaseIO.php on line 163
```

**Comment by dclipca** [comment]
hard to understand what is the exact problem

start from a new ubuntu instance and install everything again
follow every step of the instruction
