### ISSUE TITLE
Failure while npm install

### ISSUE THREAD

**Issue by thedepartedpie** [eckmarcommunity/eckmar#26]
''' npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated svgo@0.7.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
loadDep:is-binary-path    \ |###################################------------------------------------------------------|
npm ERR! Linux 4.4.0-1128-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/eckmar/npm-debug.log '''

**Comment by Gralien** [comment]
versions check

**Comment by pwnsociety** [comment]
which version does this script use

**Comment by Gralien** [comment]
php 7.4
java 8
node 10
elasticsearch
NPM
database/coin connection .env
Laravel 5.7

**Comment by pwnsociety** [comment]
they are many errors when you try to run this command npm install and npm run prod

**Comment by MxZoldyck** [comment]
i have question is this script v2 of eckmar script or v1

**Comment by pwnsociety** [comment]
i have question is this script v2 of eckmar script or v1

**Comment by joshythecoder** [comment]
> i have question is this script v2 of eckmar script or v1

**This is V2**

**Comment by Blackhawke** [comment]
I am getting a similar error on Ubuntu 18.04: It says "This is an error with npm itself. Please report this error at:..."
So, I'm posting it here:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '-g', 'localtunnel' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData localtunnel
8 silly fetchNamedPackageData localtunnel
9 silly mapToRegistry name localtunnel
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/localtunnel
13 verbose request uri https://registry.npmjs.org/localtunnel
14 verbose request no auth needed
15 info attempt registry request try #1 at 12:51:09 PM
16 verbose request id 26311079d9ef5d7f
17 verbose etag W/"405762706f9eaa2d89b5e52db1c82bfa"
18 verbose lastModified Sun, 19 Jun 2022 13:23:37 GMT
19 http request GET https://registry.npmjs.org/localtunnel
20 http 304 https://registry.npmjs.org/localtunnel
21 verbose headers { date: 'Mon, 15 Aug 2022 19:51:10 GMT',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'cf-ray': '73b476a01e8696d2-SJC',
21 verbose headers   age: '142',
21 verbose headers   'cache-control': 'public, max-age=300',
21 verbose headers   etag: '"405762706f9eaa2d89b5e52db1c82bfa"',
21 verbose headers   'last-modified': 'Sun, 19 Jun 2022 13:23:37 GMT',
21 verbose headers   vary: 'Accept-Encoding',
21 verbose headers   'cf-cache-status': 'HIT',
21 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
21 verbose headers   'x-amz-replication-status': 'COMPLETED',
21 verbose headers   server: 'cloudflare' }
22 silly get cb [ 304,
22 silly get   { date: 'Mon, 15 Aug 2022 19:51:10 GMT',
22 silly get     connection: 'keep-alive',
22 silly get     'cf-ray': '73b476a01e8696d2-SJC',
22 silly get     age: '142',
22 silly get     'cache-control': 'public, max-age=300',
22 silly get     etag: '"405762706f9eaa2d89b5e52db1c82bfa"',
22 silly get     'last-modified': 'Sun, 19 Jun 2022 13:23:37 GMT',
22 silly get     vary: 'Accept-Encoding',
22 silly get     'cf-cache-status': 'HIT',
22 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
22 silly get     'x-amz-replication-status': 'COMPLETED',
22 silly get     server: 'cloudflare' } ]
23 verbose etag https://registry.npmjs.org/localtunnel from cache
24 verbose get saving localtunnel to /home/michael/.npm/registry.npmjs.org/localtunnel/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly resolveWithNewModule localtunnel@2.0.2 checking installable status
38 silly cache add args [ 'localtunnel', null ]
39 verbose cache add spec localtunnel
40 silly cache add parsed spec Result {
40 silly cache add   raw: 'localtunnel',
40 silly cache add   scope: null,
40 silly cache add   name: 'localtunnel',
40 silly cache add   rawSpec: '',
40 silly cache add   spec: 'latest',
40 silly cache add   type: 'tag' }
41 silly addNamed localtunnel@latest
42 verbose addNamed "latest" is being treated as a dist-tag for localtunnel
43 info addNameTag [ 'localtunnel', 'latest' ]
44 silly mapToRegistry name localtunnel
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry uri https://registry.npmjs.org/localtunnel
48 verbose addNameTag registry:https://registry.npmjs.org/localtunnel not in flight; fetching
49 verbose get https://registry.npmjs.org/localtunnel not expired, no request
50 silly addNameTag next cb for localtunnel with tag latest
51 silly addNamed localtunnel@2.0.2
52 verbose addNamed "2.0.2" is a plain semver version for localtunnel
53 silly cache afterAdd localtunnel@2.0.2
54 verbose afterAdd /home/michael/.npm/localtunnel/2.0.2/package/package.json not in flight; writing
55 verbose afterAdd /home/michael/.npm/localtunnel/2.0.2/package/package.json written
56 silly fetchNamedPackageData axios
57 silly mapToRegistry name axios
58 silly mapToRegistry using default registry
59 silly mapToRegistry registry https://registry.npmjs.org/
60 silly mapToRegistry uri https://registry.npmjs.org/axios
61 silly fetchNamedPackageData debug
62 silly mapToRegistry name debug
63 silly mapToRegistry using default registry
64 silly mapToRegistry registry https://registry.npmjs.org/
65 silly mapToRegistry uri https://registry.npmjs.org/debug
66 silly fetchNamedPackageData openurl
67 silly mapToRegistry name openurl
68 silly mapToRegistry using default registry
69 silly mapToRegistry registry https://registry.npmjs.org/
70 silly mapToRegistry uri https://registry.npmjs.org/openurl
71 silly fetchNamedPackageData yargs
72 silly mapToRegistry name yargs
73 silly mapToRegistry using default registry
74 silly mapToRegistry registry https://registry.npmjs.org/
75 silly mapToRegistry uri https://registry.npmjs.org/yargs
76 verbose request uri https://registry.npmjs.org/openurl
77 verbose request no auth needed
78 info attempt registry request try #1 at 12:51:10 PM
79 verbose etag W/"8358aa40c9cfd0ce355550e5221a6e30"
80 verbose lastModified Thu, 23 Jun 2022 00:34:51 GMT
81 http request GET https://registry.npmjs.org/openurl
82 verbose request uri https://registry.npmjs.org/axios
83 verbose request no auth needed
84 info attempt registry request try #1 at 12:51:10 PM
85 verbose etag W/"3819831d42eb8afd2197ab520c824f35"
86 verbose lastModified Sun, 14 Aug 2022 16:53:54 GMT
87 http request GET https://registry.npmjs.org/axios
88 verbose request uri https://registry.npmjs.org/debug
89 verbose request no auth needed
90 info attempt registry request try #1 at 12:51:10 PM
91 verbose etag W/"51d9616cb0ee2b212bcf304eb7700c56"
92 verbose lastModified Tue, 09 Aug 2022 12:45:46 GMT
93 http request GET https://registry.npmjs.org/debug
94 verbose request uri https://registry.npmjs.org/yargs
95 verbose request no auth needed
96 info attempt registry request try #1 at 12:51:10 PM
97 verbose etag W/"6067fb57685b1ca12f09efa078f7f53f"
98 verbose lastModified Wed, 10 Aug 2022 09:44:35 GMT
99 http request GET https://registry.npmjs.org/yargs
100 http 304 https://registry.npmjs.org/openurl
101 verbose headers { date: 'Mon, 15 Aug 2022 19:51:10 GMT',
101 verbose headers   connection: 'keep-alive',
101 verbose headers   'cf-ray': '73b476a1184696d2-SJC',
101 verbose headers   'cache-control': 'public, max-age=300',
101 verbose headers   etag: '"8358aa40c9cfd0ce355550e5221a6e30"',
101 verbose headers   'last-modified': 'Thu, 23 Jun 2022 00:34:51 GMT',
101 verbose headers   vary: 'Accept-Encoding',
101 verbose headers   'cf-cache-status': 'REVALIDATED',
101 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
101 verbose headers   'x-amz-replication-status': 'COMPLETED',
101 verbose headers   server: 'cloudflare' }
102 silly get cb [ 304,
102 silly get   { date: 'Mon, 15 Aug 2022 19:51:10 GMT',
102 silly get     connection: 'keep-alive',
102 silly get     'cf-ray': '73b476a1184696d2-SJC',
102 silly get     'cache-control': 'public, max-age=300',
102 silly get     etag: '"8358aa40c9cfd0ce355550e5221a6e30"',
102 silly get     'last-modified': 'Thu, 23 Jun 2022 00:34:51 GMT',
102 silly get     vary: 'Accept-Encoding',
102 silly get     'cf-cache-status': 'REVALIDATED',
102 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
102 silly get     'x-amz-replication-status': 'COMPLETED',
102 silly get     server: 'cloudflare' } ]
103 verbose etag https://registry.npmjs.org/openurl from cache
104 verbose get saving openurl to /home/michael/.npm/registry.npmjs.org/openurl/.cache.json
105 silly resolveWithNewModule openurl@1.1.1 checking installable status
106 silly cache add args [ 'openurl@1.1.1', null ]
107 verbose cache add spec openurl@1.1.1
108 silly cache add parsed spec Result {
108 silly cache add   raw: 'openurl@1.1.1',
108 silly cache add   scope: null,
108 silly cache add   name: 'openurl',
108 silly cache add   rawSpec: '1.1.1',
108 silly cache add   spec: '1.1.1',
108 silly cache add   type: 'version' }
109 silly addNamed openurl@1.1.1
110 verbose addNamed "1.1.1" is a plain semver version for openurl
111 silly mapToRegistry name openurl
112 silly mapToRegistry using default registry
113 silly mapToRegistry registry https://registry.npmjs.org/
114 silly mapToRegistry uri https://registry.npmjs.org/openurl
115 verbose addNameVersion registry:https://registry.npmjs.org/openurl not in flight; fetching
116 verbose get https://registry.npmjs.org/openurl not expired, no request
117 silly cache afterAdd openurl@1.1.1
118 verbose afterAdd /home/michael/.npm/openurl/1.1.1/package/package.json not in flight; writing
119 verbose afterAdd /home/michael/.npm/openurl/1.1.1/package/package.json written
120 http 304 https://registry.npmjs.org/debug
121 verbose headers { date: 'Mon, 15 Aug 2022 19:51:10 GMT',
121 verbose headers   connection: 'keep-alive',
121 verbose headers   'cf-ray': '73b476a22e859429-SJC',
121 verbose headers   age: '96',
121 verbose headers   'cache-control': 'public, max-age=300',
121 verbose headers   etag: '"51d9616cb0ee2b212bcf304eb7700c56"',
121 verbose headers   'last-modified': 'Tue, 09 Aug 2022 12:45:46 GMT',
121 verbose headers   vary: 'Accept-Encoding',
121 verbose headers   'cf-cache-status': 'HIT',
121 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
121 verbose headers   'x-amz-replication-status': 'PENDING',
121 verbose headers   server: 'cloudflare' }
122 silly get cb [ 304,
122 silly get   { date: 'Mon, 15 Aug 2022 19:51:10 GMT',
122 silly get     connection: 'keep-alive',
122 silly get     'cf-ray': '73b476a22e859429-SJC',
122 silly get     age: '96',
122 silly get     'cache-control': 'public, max-age=300',
122 silly get     etag: '"51d9616cb0ee2b212bcf304eb7700c56"',
122 silly get     'last-modified': 'Tue, 09 Aug 2022 12:45:46 GMT',
122 silly get     vary: 'Accept-Encoding',
122 silly get     'cf-cache-status': 'HIT',
122 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
122 silly get     'x-amz-replication-status': 'PENDING',
122 silly get     server: 'cloudflare' } ]
123 verbose etag https://registry.npmjs.org/debug from cache
124 verbose get saving debug to /home/michael/.npm/registry.npmjs.org/debug/.cache.json
125 silly resolveWithNewModule debug@4.3.2 checking installable status
126 silly cache add args [ 'debug@4.3.2', null ]
127 verbose cache add spec debug@4.3.2
128 silly cache add parsed spec Result {
128 silly cache add   raw: 'debug@4.3.2',
128 silly cache add   scope: null,
128 silly cache add   name: 'debug',
128 silly cache add   rawSpec: '4.3.2',
128 silly cache add   spec: '4.3.2',
128 silly cache add   type: 'version' }
129 silly addNamed debug@4.3.2
130 verbose addNamed "4.3.2" is a plain semver version for debug
131 silly mapToRegistry name debug
132 silly mapToRegistry using default registry
133 silly mapToRegistry registry https://registry.npmjs.org/
134 silly mapToRegistry uri https://registry.npmjs.org/debug
135 verbose addNameVersion registry:https://registry.npmjs.org/debug not in flight; fetching
136 verbose get https://registry.npmjs.org/debug not expired, no request
137 silly cache afterAdd debug@4.3.2
138 verbose afterAdd /home/michael/.npm/debug/4.3.2/package/package.json not in flight; writing
139 verbose afterAdd /home/michael/.npm/debug/4.3.2/package/package.json written
140 http 304 https://registry.npmjs.org/axios
141 verbose headers { date: 'Mon, 15 Aug 2022 19:51:10 GMT',
141 verbose headers   connection: 'keep-alive',
141 verbose headers   'cf-ray': '73b476a22bcc9675-SJC',
141 verbose headers   'cache-control': 'public, max-age=300',
141 verbose headers   etag: '"3819831d42eb8afd2197ab520c824f35"',
141 verbose headers   'last-modified': 'Sun, 14 Aug 2022 16:53:54 GMT',
141 verbose headers   vary: 'Accept-Encoding',
141 verbose headers   'cf-cache-status': 'REVALIDATED',
141 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
141 verbose headers   'x-amz-replication-status': 'COMPLETED',
141 verbose headers   server: 'cloudflare' }
142 silly get cb [ 304,
142 silly get   { date: 'Mon, 15 Aug 2022 19:51:10 GMT',
142 silly get     connection: 'keep-alive',
142 silly get     'cf-ray': '73b476a22bcc9675-SJC',
142 silly get     'cache-control': 'public, max-age=300',
142 silly get     etag: '"3819831d42eb8afd2197ab520c824f35"',
142 silly get     'last-modified': 'Sun, 14 Aug 2022 16:53:54 GMT',
142 silly get     vary: 'Accept-Encoding',
142 silly get     'cf-cache-status': 'REVALIDATED',
142 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
142 silly get     'x-amz-replication-status': 'COMPLETED',
142 silly get     server: 'cloudflare' } ]
143 verbose etag https://registry.npmjs.org/axios from cache
144 verbose get saving axios to /home/michael/.npm/registry.npmjs.org/axios/.cache.json
145 http 304 https://registry.npmjs.org/yargs
146 verbose headers { date: 'Mon, 15 Aug 2022 19:51:10 GMT',
146 verbose headers   connection: 'keep-alive',
146 verbose headers   'cf-ray': '73b476a22a0e9878-SJC',
146 verbose headers   age: '235',
146 verbose headers   'cache-control': 'public, max-age=300',
146 verbose headers   etag: '"6067fb57685b1ca12f09efa078f7f53f"',
146 verbose headers   'last-modified': 'Wed, 10 Aug 2022 09:44:35 GMT',
146 verbose headers   vary: 'Accept-Encoding',
146 verbose headers   'cf-cache-status': 'HIT',
146 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
146 verbose headers   'x-amz-replication-status': 'COMPLETED',
146 verbose headers   server: 'cloudflare' }
147 silly get cb [ 304,
147 silly get   { date: 'Mon, 15 Aug 2022 19:51:10 GMT',
147 silly get     connection: 'keep-alive',
147 silly get     'cf-ray': '73b476a22a0e9878-SJC',
147 silly get     age: '235',
147 silly get     'cache-control': 'public, max-age=300',
147 silly get     etag: '"6067fb57685b1ca12f09efa078f7f53f"',
147 silly get     'last-modified': 'Wed, 10 Aug 2022 09:44:35 GMT',
147 silly get     vary: 'Accept-Encoding',
147 silly get     'cf-cache-status': 'HIT',
147 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
147 silly get     'x-amz-replication-status': 'COMPLETED',
147 silly get     server: 'cloudflare' } ]
148 verbose etag https://registry.npmjs.org/yargs from cache
149 verbose get saving yargs to /home/michael/.npm/registry.npmjs.org/yargs/.cache.json
150 silly resolveWithNewModule axios@0.21.4 checking installable status
151 silly cache add args [ 'axios@0.21.4', null ]
152 verbose cache add spec axios@0.21.4
153 silly cache add parsed spec Result {
153 silly cache add   raw: 'axios@0.21.4',
153 silly cache add   scope: null,
153 silly cache add   name: 'axios',
153 silly cache add   rawSpec: '0.21.4',
153 silly cache add   spec: '0.21.4',
153 silly cache add   type: 'version' }
154 silly addNamed axios@0.21.4
155 verbose addNamed "0.21.4" is a plain semver version for axios
156 silly mapToRegistry name axios
157 silly mapToRegistry using default registry
158 silly mapToRegistry registry https://registry.npmjs.org/
159 silly mapToRegistry uri https://registry.npmjs.org/axios
160 verbose addNameVersion registry:https://registry.npmjs.org/axios not in flight; fetching
161 verbose get https://registry.npmjs.org/axios not expired, no request
162 verbose stack Error: Missing required argument #1
162 verbose stack     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
162 verbose stack     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
162 verbose stack     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
162 verbose stack     at /usr/share/npm/lib/install/deps.js:457:7
162 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
162 verbose stack     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
162 verbose stack     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
162 verbose stack     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
162 verbose stack     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
162 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
163 verbose cwd /etc
164 error Linux 4.15.0-189-generic
165 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "localtunnel"
166 error node v8.10.0
167 error npm  v3.5.2
168 error code EMISSINGARG
169 error typeerror Error: Missing required argument #1
169 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
169 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
169 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
169 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
169 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
169 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
169 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
169 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
169 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
169 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
170 error typeerror This is an error with npm itself. Please report this error at:
170 error typeerror     <http://github.com/npm/npm/issues>
171 verbose exit [ 1, true ]

**Comment by kushalg-1212** [comment]
i did not read the entire error but using node version 7 helped me

**Comment by justrawdata** [comment]
Here's a step-by-step solution!

Just use these commands (in order) when you get to the error.

npm install -g n   	# Install n globally
n uninstall		# Uninstall current
n 7.7.0			# Install and use v7.7.0
hash -r 		# Update pathing

node -v			#If 7.7.0, you're good to go! Use npm install

**Comment by Gralien** [comment]
Easy questions, you are supposed to let them figure this out themselves
guys. 😗 Otherwise...some one might get in trouble with this. 😂🤣🔥 Nice
