### ISSUE TITLE
Issue while installing Php

### ISSUE THREAD

**Issue by notjustcodes** [eckmarcommunity/eckmar#27]
Hello,
When i try to install php by using "sudo apt-get install php7.2-fpm php-mysql"

i get the following error ↓↓↓ , ( I also attached the screenshot )

E: Unable to locate package php7.2-fpm
E: Couldn't find any package by glob 'php7.2-fpm'
E: Couldn't find any package by regex 'php7.2-fpm'

![php error](https://user-images.githubusercontent.com/107455731/176610806-d2e7b98f-0092-471e-be97-e5e775b50852.png)

**Comment by dclipca** [comment]
Did you do ```sudo apt update```. Just in case, execute every instruction before ``sudo apt-get install php7.2-fpm php-mysql`, i.e. start from scratch.
