### ISSUE TITLE
How to setup cryptocurrency payment on marketplace

### ISSUE THREAD

**Issue by MxZoldyck** [eckmarcommunity/eckmar#32]
Can someone explain How to Connect coins with mareketplace

**Comment by MxZoldyck** [comment]
Any hints or suggestions I would appreciate

**Comment by Gralien** [comment]
so...the coins all follow the same scheme
this is what the coin-rpc wallets are for are for.
files
.env (database)
coins.php (coin settings)

you will need a local node or a remote node to hash on via RPC connections.
Install any of the coins nodes (you'll need some disk space, lol)
you can do this over TOR or LOCALHOST.
Run the node as a dameon in the background, detached and enabled or via "screen".

open a new terminal and "screen" it and run the commands. you may use ./monero-wallet-rpc, or ./bitcoind-rpc, or ./litecoind-rpc
concept is the same

run your CLI
monero example....
Linux (Production Example) format
./monero-wallet-rpc --rpc-bind-port 28088 --wallet-file wallets/main/main --password walletPassword --rpc-login monero:rpcPassword --log-file logs/monero-wallet-rpc.log --max-log-files 2 --trusted-daemon --non-interactive

ex.

local
/monero-wallet-rpc --rpc-bind-port 18082 --wallet-file <yourwalletname> --prompt-for-password --rpc-login <makeusrname>:<makepass> --log-file logs/monero-wallet-rpc.log --log level 1

remote over TOR;
./monero-wallet-rpc --rpc-bind-port 18082 --proxy 127.0.0.1:9150 --daemon-host youronionaddresshere(orremotehost).onion --confirm-external-bind --wallet-file <yourwalletname> --prompt-for-password --rpc-login <makeusrname>:<makepass> --trusted-daemon --log-file logs/monero-wallet-rpc.log --log-level 1

plenty of other commands available to substitute.

Now, as for laravel application eckmar;
config/coins.php
// UN-comment the coin you are working with or use multiples.

    'coin_list' => [       
        'btc' => \App\Marketplace\Payment\BitcoinPayment::class,
//       'btcm' => \App\Marketplace\Payment\BitcoinMutlisig::class, // bitcoin multisig
        'xmr' => \App\Marketplace\Payment\MoneroPayment::class,
//        'stb' => \App\Marketplace\Payment\StubCoin::class,
//        'pivx' => \App\Marketplace\Payment\PivxCoin::class,
//        'ltc' => \App\Marketplace\Payment\LitecoinPayment::class,
//        'dash' => \App\Marketplace\Payment\DashPayment::class,
//        'bch' => \App\Marketplace\Payment\BitcoinCashPayment::class,
//        'xvg' => \App\Marketplace\Payment\VergeCoin::class,
    ],
...

// this is where you put the RPC username and passwords in your RPC commands above.
//-rpc-login <makeusrname>:<makepass>

     */
    'bitcoin' => [
        'host' => env('BITCOIND_HOST', 'localhost'),
        'username' => env('BITCOIND_USERNAME', 'RPCUSER'),
        'password' => env('BITCOIND_PASSWORD', 'RPCPASS'),
        'port' => env('BITCOIND_PORT', 8332),
        'minconfirmations' => env('BITCOIND_MINCONFIRMATIONS', 1),
    ],


    /**
     * Monero settings
     *
     * Uses data from .env file
     */

    'monero' => [
        'host' => env('MONERO_HOST', '127.0.0.1'),
        'port' => intval(env('MONERO_PORT', 18082)),
        'username' => env('MONERO_USERNAME', 'RPCUSER'),
        'password' => env('MONERO_PASSWORD', 'RPCPASS')
    ],

lets look at that "hidden" .env file refered to....
its in the root folder
nano .env from as root from web folder root.

MONERO_HOST=127.0.0.1
MONERO_PORT=18082
MONERO_USERNAME=RPCUSER              
MONERO_PASSWORD=RPCPASS

BITCOIND_HOST=127.0.0.1
BITCOIND_PORT=8332
BITCOIND_USERNAME=RPCPASS
BITCOIND_PASSWORD=RPCUSER

other important settings are in this file too...

don't forget to clear your config and cache after every edit.
php artisan config:clear
php artisan cache:clear

please donate and send me a PM after
XMR
44yqQwSCZob6ox3d8gFxJPaegEy3SCTTbjKgkXcQdmYsJm2VMR1aHCm5Y2zdfnHuPS2LEfAXZoK8j4cNr4k3yeR5HcCos5a 
access to the XMR remote nodes to hash to over TOR if you wish. then you don't have to run your own private node for monero if that's what you are using.

Side notes;
be port aware and match values in RPC calls and files.
make sure nodes are synced with the network before launching coin-rpc
RPC and dameon must be running, node synced, then RPC wallet up and left running to listen for active RPC connections, incomming or local.

**Comment by kjmario78** [comment]
monerod running 
monero-wallet-rpc running 
and backend doesn't show any address, why?

![image](https://user-images.githubusercontent.com/3342394/178350371-a1737724-90aa-4f50-91b7-66036790a0a1.png)

**Comment by Gralien** [comment]
you need to set a market address?

**Comment by kjmario78** [comment]
> you need to set a market address?

already done, where am I wrong?? 

```
    'coin_list' => [
//        'btc' => \App\Marketplace\Payment\BitcoinPayment::class,
//        'btcm' => \App\Marketplace\Payment\BitcoinMutlisig::class, // bitcoin multisig
        'xmr' => \App\Marketplace\Payment\MoneroPayment::class,
//        'stb' => \App\Marketplace\Payment\StubCoin::class,

```
```
    'market_addresses' => [
      'xmr' => [ // list of btc addresses
          ' my monero address',
      ],
```

**Comment by MxZoldyck** [comment]
I think that you need Monero node Payment method 
https://demo.botdigit.com/product/monero-node-payment-method-for-eckmars-marketplace-script/

**Comment by kjmario78** [comment]
> I think that you need Monero node Payment method https://demo.botdigit.com/product/monero-node-payment-method-for-eckmars-marketplace-script/

aren't these?

![image](https://user-images.githubusercontent.com/3342394/178989522-5f15a888-eaa1-4e99-879b-09ca020c32a1.png)

**Comment by Gralien** [comment]
'market_addresses' => [
                 'xmr' => [ // list of btc addresses
                 ' my monero address',
      ],

take the comment out of the brackets. remove the quotes around your monero address?
your RPC connection should be open with the address you set as well.

**Comment by MxZoldyck** [comment]
You can use bitcoin pruning mode or monero pruning mode to save Some space

**Comment by kjmario78** [comment]
> ```
> 'market_addresses' => [
>              'xmr' => [ // list of btc addresses
>              ' my monero address',
>   ],
> ```
> 
> take the comment out of the brackets. remove the quotes around your monero address? your RPC connection should be open with the address you set as well.


quotes around address present.
Rpc connection open, I tested it with curl and works.
From logs I not see any call from market code.

**Comment by MxZoldyck** [comment]
Does Anyone here fix it

> monerod running monero-wallet-rpc running and backend doesn't show any address, why?
> 
> ![image](https://user-images.githubusercontent.com/3342394/178350371-a1737724-90aa-4f50-91b7-66036790a0a1.png)

**Comment by MxZoldyck** [comment]
how to fix it
bitcoin.conf
rpcuser=myuser
rpcpassword=mypassword
#testnet=1
rpcport=18332
rpcallowip=127.0.0.1
server=1
prune=16000
wallet=testwallet

**Comment by ffeel31** [comment]
Please i need help. I have done all configurations but the problem now is how do it add fund to my wallet such that i can see my current balance and be able to pay and become a vendor.

![eckmar add funds](https://github.com/eckmarcommunity/eckmar/assets/152450002/504fffbe-f812-4d5d-ab77-cf64238d7d02)

as you can in the image, balance is unavailable. how can i make it available ?
