### ISSUE TITLE
How to change coin?

### ISSUE THREAD

**Issue by Sebbeger** [eckmarcommunity/eckmar#34]
Right now i have the coin STB and try to use BTC instead. I have been looking everywhere how to change it...
Where do i change it from STB to BTC?

**Comment by Sebbeger** [comment]
When i try to comment those coins i dont want, i get this error:


(1/1)                                     ErrorException                                                                  RecursiveDirectoryIterator::hasChildren():  open_basedir restriction in effect.  File(/www/wwwroot/someaddress.onion/phpmyadmin)  is not within the allowed path(s):  (/www/wwwroot/someaddress.onion/:/tmp/)
--
in ExcludeDirectoryFilterIterator.php line 73
at HandleExceptions->handleError()
at RecursiveDirectoryIterator->hasChildren()in ExcludeDirectoryFilterIterator.php line 73
at ExcludeDirectoryFilterIterator->hasChildren()
at FilterIterator->next()
at FilterIterator->rewind()
at FilterIterator->rewind()
etc etc etc

**Comment by MxZoldyck** [comment]
same issue

**Comment by MxZoldyck** [comment]
Any update about this error ?

**Comment by MxZoldyck** [comment]
after you comment you need to make new account

**Comment by botdigit-admin** [comment]
change coin from STB to BTC in config/coin.php  then clear config cache  then migrate database again 
` php artisan migrate:fresh`

**Comment by Sebbeger** [comment]
When i did that, the only thing that happened was that i couldent log in.
So i still have the same problem but now with Monero
