### ISSUE TITLE
monero doesn't work 

### ISSUE THREAD

**Issue by kjmario78** [eckmarcommunity/eckmar#35]
monerod running 
monero-wallet-rpc running 
and backend doesn't show any address, why?

![image](https://user-images.githubusercontent.com/3342394/178350371-a1737724-90aa-4f50-91b7-66036790a0a1.png)

_Originally posted by @kjmario78 in https://github.com/eckmarcommunity/eckmar/issues/32#issuecomment-1180827970_

**Comment by dclipca** [comment]
https://github.com/eckmarcommunity/eckmar/issues/32

you checked this issue right?

**Comment by kjmario78** [comment]
> #32
> 
> you checked this issue right?

ofc

**Comment by botdigit-admin** [comment]
you need to check your monero working fine you can test with like this on comamnd like if it retrun response then check you cred for monero  on .env and clear cache 


` Curl -u monero:99U1WURpLIO0Q== --digest http://127.0.0.1:18081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_balance","params":{"account_index":0,"address_indices":[0,1]}}' -H 'Content-Type: application/json'`

**Comment by kjmario78** [comment]
> you need to check your monero working fine you can test with like this on comamnd like if it retrun response then check you cred for monero on .env and clear cache
> 
> ` Curl -u monero:99U1WURpLIO0Q== --digest http://127.0.0.1:18081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_balance","params":{"account_index":0,"address_indices":[0,1]}}' -H 'Content-Type: application/json'`

my monero node works fine, I checked it with curl.

**Comment by botdigit-admin** [comment]
> > you need to check your monero working fine you can test with like this on comamnd like if it retrun response then check you cred for monero on .env and clear cache
> > ` Curl -u monero:99U1WURpLIO0Q== --digest http://127.0.0.1:18081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_balance","params":{"account_index":0,"address_indices":[0,1]}}' -H 'Content-Type: application/json'`
> 
> my monero node works fine, I checked it with curl.

then just check config and clear cache in new user register it will create new address it wil not create address for old user allready created

**Comment by kjmario78** [comment]
> > > you need to check your monero working fine you can test with like this on comamnd like if it retrun response then check you cred for monero on .env and clear cache
> > > ` Curl -u monero:99U1WURpLIO0Q== --digest http://127.0.0.1:18081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_balance","params":{"account_index":0,"address_indices":[0,1]}}' -H 'Content-Type: application/json'`
> > 
> > 
> > my monero node works fine, I checked it with curl.
> 
> then just check config and clear cache in new user register it will create new address it wil not create address for old user allready created

thank you. In my test I have not considered to create a new user.
