### ISSUE TITLE
InvalidArgumentException : Invalid CRON field value 30 at position 4

### ISSUE THREAD

**Issue by EckmarV2** [eckmarcommunity/eckmar#36]
I tried To run this command **php artisan schedule:run**  I got this error
```
InvalidArgumentException : Invalid CRON field value 30 at position 4
at /var/www/vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php:155
    151|      */
    152|     public function setPart($position, $value)
    153|     {
    154|         if (!$this->fieldFactory->getField($position)->validate($value)) {
  > 155|             throw new InvalidArgumentException(
    156|                 'Invalid CRON field value ' . $value . ' at position ' . $position
    157|             );
    158|         }
    159|

```
this is command on my Kernel Path app/Console/Kernel.php

```
    protected function schedule(Schedule $schedule)
    {
        // Schedule to delete old messages every old days
        $schedule -> command(DeleteOldMessages::class, ['days' => config('marketplace.days_old_messages')])
                    ->days(config('marketplace.days_old_messages'));

        // Make the command for releasing purchases runs each X days
        $schedule -> command(ReleasePurchasesCommand::class, ['days' => config('marketplace.days_old_purchases')])
                    ->days(config('marketplace.days_old_purchases'));

        // Run completing command for purchases every defined number of days
        $schedule -> command(CompletePurchaseCommand::class) -> days(config('marketplace.days_complete'));

    }
```

Thanks in advance for any help.

**Comment by botdigit-admin** [comment]
` protected function schedule(Schedule $schedule)
    {
        // Schedule to delete old messages every old days
      //  $schedule -> command(DeleteOldMessages::class, ['days' => config('marketplace.days_old_messages')])
     //               ->days(config('marketplace.days_old_messages'));

        // Make the command for releasing purchases runs each X days
//        $schedule -> command(ReleasePurchasesCommand::class, ['days' => config('marketplace.days_old_purchases')]) ->days(config('marketplace.days_old_purc>
//      $schedule->command(new ReleasePurchasesCommand)->days(config('marketplace.days_old_purchases'));
        // Run completing command for purchases every defined number of days
        $schedule -> command(CompletePurchaseCommand::class) -> days(config('marketplace.days_complete'));
        $schedule->command(ReleasePurchasesCommand::class, ['days' => config('marketplace.days_old_purchases')])->daily();
    }

`

**Comment by EckmarV2** [comment]
do i need to change something on marketplace.php and do i need to add any commands on cron ?

**Comment by botdigit-admin** [comment]
you only need to change in app/Console/Kernel.php
cron command will be normal as use in other laravel 

[https://stackoverflow.com/questions/41906034/laravel-task-scheduler-crontab](https://stackoverflow.com/questions/41906034/laravel-task-scheduler-crontab)

its basic of laravel if you need more help in this must follow laravel

**Comment by Eckmar2** [comment]
Hi I tried everything you say it still not working
