### ISSUE TITLE
FE module Not Working

### ISSUE THREAD

**Issue by EckmarV2** [eckmarcommunity/eckmar#37]
I bought FE module From https://demo.botdigit.com/ it seems not working

**Comment by EckmarV2** [comment]
I contact support team he say that issue has something to do with cron

**Comment by botdigit-admin** [comment]
FE functionally  works with corn it check order status and change  like processing ,pending ,etc  for auto check cron must run

**Comment by Eckmar2** [comment]
Hi I tried everything you say it still not working

**Comment by ffeel31** [comment]
Inside the Modules folder, there is no FE there only the Featured Product module. how then do we use the FE functionality?
