### ISSUE TITLE
How to hide categories from not logged in?

### ISSUE THREAD

**Issue by Sebbeger** [eckmarcommunity/eckmar#38]
I want to hide the catogories for not logged in guests and replace the categories with a login box.
How do i do that?

**Comment by dclipca** [comment]
That would require Laravel knowledge and knoledge of how auth in Eckmar works. @botdigit-admin and @Gralien might have the required expertise.

**Comment by botdigit-admin** [comment]
@if(auth() )
 categories  html 
 
 @else
login html 
@endif
