### ISSUE TITLE
Pictures not loading 

### ISSUE THREAD

**Issue by kushalg-1212** [eckmarcommunity/eckmar#39]
Firstly would like to thank you for making this OS 

I did a test installation of this script  
ran into a lop of problems , especially with npm 
but after managing to install the script successfully i cant see the images  of the seeded demo products , is it default that there is no image or am i missing something here

**Comment by Sebbeger** [comment]
Have you linked the storage? php artisan link:storage

**Comment by Gralien** [comment]
Also folder permissions should be checked
