### ISSUE TITLE
Pictures are not loading

### ISSUE THREAD

**Issue by ummuttkkarip** [eckmarcommunity/eckmar#41]
I installed everything and created a products from phpmyadmin.
Than entered to admin panel and added a picture to products.
But when I go to the product page the picture is not loading.
<img width="189" alt="image" src="https://user-images.githubusercontent.com/109227859/186175876-8529789e-d483-4c5d-9f73-dc9a40976c55.png">
<img width="536" alt="image" src="https://user-images.githubusercontent.com/109227859/186175970-b16d7dd7-5d7f-49ba-9621-fb0899390fb3.png">

**Comment by thisisforjimmy** [comment]
I would check the permissions to the storage and make sure all other permissions were setup correctly. See below.
[https://github.com/eckmarcommunity/eckmar/blob/master/INSTALLATION.md#permissions](https://github.com/eckmarcommunity/eckmar/blob/master/INSTALLATION.md#permissions)

**Comment by Gralien** [comment]
And ownership groups

**Comment by dclipca** [comment]
I second. This is very likely related to permissions.

**Comment by botdigit-admin** [comment]
it looks like you did not upload images you may created product with database create product from vendor account and upload images if images still not load check storage link 

https://stackoverflow.com/questions/50185273/laravel-5-4-storage-link

**Comment by rootkit228** [comment]
bro create a symbolic link
ln -s /var/www/eckmar/storage/app/public /var/www/eckmar/public/storage

**Comment by rootkit228** [comment]
> I installed everything and created a products from phpmyadmin. Than entered to admin panel and added a picture to products. But when I go to the product page the picture is not loading. <img alt="image" width="189" src="https://user-images.githubusercontent.com/109227859/186175876-8529789e-d483-4c5d-9f73-dc9a40976c55.png"> <img alt="image" width="536" src="https://user-images.githubusercontent.com/109227859/186175970-b16d7dd7-5d7f-49ba-9621-fb0899390fb3.png">

bro create a symbolic link
ln -s /var/www/eckmar/storage/app/public /var/www/eckmar/public/storage
