### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by ummuttkkarip** [eckmarcommunity/eckmar#42]
I wanted to add a PGP key but it says Array and string offset access syntax with curly braces is deprecated
<img width="884" alt="image" src="https://user-images.githubusercontent.com/109227859/186178879-d263cd8e-d5c9-49cc-969e-c0debbed724f.png">

**Comment by thisisforjimmy** [comment]
I had the same issue and found that you can only use RSA 4096 PGP KEYS ONLY. Give it a shot and let me know if it fixes the problem.

**Comment by Gralien** [comment]
that is not a true statement.

**Comment by botdigit-admin** [comment]
check you PHP version if you want to change latest php you need to change like {0} to [0]
https://stackoverflow.com/questions/59158548/array-and-string-offset-access-syntax-with-curly-braces-is-deprecated
