### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by frostytsnowman** [eckmarcommunity/eckmar#43]
"500 Internal Server Error, nginx/1.14.0 (Ubuntu)" what did I do wrong here. has anyone else had this problem, if so how do I fix it?

**Comment by dclipca** [comment]
Can you looking into the errors?
```
Nginx HTTP server has a highly customizable and outstanding logging facility. Nginx writes the information in the different severity levels debug, info, notice, warn, error, alert, and emerg to the logs. By default, the Nginx access log is located at /var/log/nginx/access.log and the error log is located at /var/log/nginx/error.log. Nginx logs file default path depends on the operating system and installation. You can override the default settings and change the format of logged messages by editing the NGINX configuration file /etc/nginx/nginx.conf .
```
More [here](https://www.loginradius.com/blog/engineering/quick-10-minutes-guide-about-the-nginx-access-and-error-logs/#:~:text=log%20and%20the%20error%20log,%2Fetc%2Fnginx%2Fnginx.).

**Comment by botdigit-admin** [comment]
enable debug and check your error   check Laravel doc how to use
