### ISSUE TITLE
PGP Confirmation error - Undefined offset: 22

### ISSUE THREAD

**Issue by desoasl44** [eckmarcommunity/eckmar#54]
Tried to add a PGP key to a test account but I get this error on the confirmation page: **Undefined offset: 22**

Here is a screenshot: 

![image](https://user-images.githubusercontent.com/112721390/201523841-e20cdaf3-cb53-4d28-b6d8-aa7a2926afbe.png)

Anyone had this error before? Can't really find a way to fix that.

Thanks in advance

**Comment by Gralien** [comment]
this must be a PHP error based on the format in which you entered the key. you may attempt to adjust the PHP to handle the formatting or you can play with the spacing adjusting the top block until it works? 

Removing the info block;

-----BEGIN PGP PUBLIC KEY BLOCK-----
white space
mRDAZQ.....
-----END PGP PUBLIC KEY BLOCK-----

eliminate this stuff
Comment: User-ID:	
Comment: Created:	
Comment: Type:	
Comment: Usage:	
Comment: Fingerprint:

maybe?

**Comment by desoasl44** [comment]
You were right, that's the issue, thanks so much! If there is comments it'll mess up the decryption message gen.
