### ISSUE TITLE
NPM issues

### ISSUE THREAD

**Issue by jackpipergit** [eckmarcommunity/eckmar#57]
Attempted different versions of node and npm. Same issue.
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/92690218/226223944-3f3e1ef8-6220-4de8-8f15-d17ea6ff27f9.png">

rest of errors
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated acorn-dynamic-import@2.0.2: This is probably built in to whatever tool you're using. If you still need it... idk
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated chokidar@2.0.4: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated source-map-resolve@0.5.2: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated har-validator@2.0.6: this library is no longer supported
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated request@2.79.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated buffer@3.6.0: This version of 'buffer' is out-of-date. You must update to v3.6.2 or newer
npm WARN deprecated tar@2.2.1: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
npm WARN deprecated axios@0.18.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm WARN deprecated svgo@0.7.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated svgo@1.0.5: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated popper.js@1.14.3: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.5.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     '/var/www/peralta/node_modules/optipng-bin',
npm WARN cleanup     [Error: ENOTEMPTY: directory not empty, rmdir '/var/www/peralta/node_modules/optipng-bin'] {
npm WARN cleanup       errno: -39,
npm WARN cleanup       code: 'ENOTEMPTY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: '/var/www/peralta/node_modules/optipng-bin'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     '/var/www/peralta/node_modules',
npm WARN cleanup     [Error: ENOTEMPTY: directory not empty, rmdir '/var/www/peralta/node_modules/optipng-bin'] {
npm WARN cleanup       errno: -39,
npm WARN cleanup       code: 'ENOTEMPTY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: '/var/www/peralta/node_modules/optipng-bin'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path /var/www/peralta/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/bin/node /var/www/peralta/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/var/www/peralta/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.7.0
npm ERR! gyp info using node@18.15.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/var/www/peralta/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/var/www/peralta/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/var/www/peralta/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /var/www/peralta/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /var/www/peralta/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /var/www/peralta/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:208:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/var/www/peralta/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/var/www/peralta/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/var/www/peralta/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /var/www/peralta/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /var/www/peralta/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /var/www/peralta/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:208:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/var/www/peralta/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/var/www/peralta/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/var/www/peralta/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /var/www/peralta/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /var/www/peralta/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /var/www/peralta/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:208:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/var/www/peralta/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/var/www/peralta/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/var/www/peralta/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /var/www/peralta/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /var/www/peralta/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /var/www/peralta/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:208:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/var/www/peralta/node_modules/node-gyp/lib/configure.js:492:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/var/www/peralta/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/var/www/peralta/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/var/www/peralta/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /var/www/peralta/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /var/www/peralta/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /var/www/peralta/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:208:21)
npm ERR! gyp ERR! System Linux 5.4.0-137-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/var/www/peralta/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /var/www/peralta/node_modules/node-sass
npm ERR! gyp ERR! node -v v18.15.0
npm ERR! gyp ERR! node-gyp -v v3.7.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

**Comment by dclipca** [comment]
Really no idea what might be the issue. I have a feeling someone had this issue before. Please scroll through the resolved issue in this repository, you might find an answer.
