### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by dacigm007** [eckmarcommunity/eckmar#58]
everything gone right but when i acess website through web browser i get this
![image](https://user-images.githubusercontent.com/65663517/232167846-488f58a1-2f89-4c8b-b7e1-f745334610d7.png)

**Comment by dclipca** [comment]
@dacigm007 can you try `localhost` instead of `127.0.0.1`? Sometimes there's a difference, especially between Linux and Windows. Also please attach the latest relevant NGINX logs. By default, NGINX writes its events in two types of logs - the error log and the access log. In most of the popular Linux distro like Ubuntu (like in this it is the case for you), CentOS or Debian, both the access and error log can be found in /var/log/nginx, assuming you have already enabled the access and error logs in the core NGINX configuration file. Let us find out more about NGINX access log, error log and how to enable them if you have not done it earlier. More about logs on https://www.digitalocean.com/community/tutorials/nginx-access-logs-error-logs.

**Comment by dacigm007** [comment]
Here is acess log as error log is empty https://easyupload.io/065lco

**Comment by dclipca** [comment]
> Here is access log as error log is empty [access.log](https://github.com/eckmarcommunity/eckmar/files/11239791/access.log)
> 
> > @dacigm007 can you try `localhost` instead of `127.0.0.1`? Sometimes there's a difference, especially between Linux and Windows. Also please attach the latest relevant NGINX logs. By default, NGINX writes its events in two types of logs - the error log and the access log. In most of the popular Linux distro like Ubuntu (I think you have Ubuntu, right?), CentOS or Debian, both the access and error log can be found in /var/log/nginx, assuming you have already enabled the access and error logs in the core NGINX configuration file. You can read more about logs on https://www.digitalocean.com/community/tutorials/nginx-access-logs-error-logs.

I think this suggests that the Eckmar files are there but there's an internal error in NGINX relating to the config. Can you attach the config?

**Comment by dacigm007** [comment]
> > Here is access log as error log is empty [access.log](https://github.com/eckmarcommunity/eckmar/files/11239791/access.log)
> > > @dacigm007 can you try `localhost` instead of `127.0.0.1`? Sometimes there's a difference, especially between Linux and Windows. Also please attach the latest relevant NGINX logs. By default, NGINX writes its events in two types of logs - the error log and the access log. In most of the popular Linux distro like Ubuntu (I think you have Ubuntu, right?), CentOS or Debian, both the access and error log can be found in /var/log/nginx, assuming you have already enabled the access and error logs in the core NGINX configuration file. You can read more about logs on https://www.digitalocean.com/community/tutorials/nginx-access-logs-error-logs.
> 
> I think this suggests that the Eckmar files are there but there's an internal error in NGINX relating to the config. Can you attach the config?

server {
        listen 80;
        listen [::]:80;
        listen 443;
        listen [::]:443;
root /var/www/eckmar/public;
index index.php index.html index.htm index.nginx-debian.html;
server_name domain.com;
location / {
try_files $uri $uri/ /index.php?$query_string;
}
location ~ \.php$ {
try_files $uri =404;
fastcgi_split_path_info ^(.+\.php)(/.+)$;
fastcgi_pass unix:/run/php/php7.2-fpm.sock;
fastcgi_index index.php;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; include fastcgi_params;
} }

**Comment by dclipca** [comment]
Can you do `sudo systemctl config nginx` to check if there are no errors in the config. Attach the logs. You can read more on https://docs.rackspace.com/support/how-to/basic-nginx-troubleshooting/#:~:text=Through%20a%20simple%20command%20you,line%20where%20the%20problem%20is.

**Comment by dclipca** [comment]
If there are no errors in the config, wipe everything from the machine and install Eckmar from scratch by strictly following https://github.com/eckmarcommunity/eckmar/blob/master/INSTALLATION.md.

**Comment by Gralien** [comment]
I'm going to say that this is a script timeout error. It may just be
throwing error because the script timed out before transaction response?

**Comment by dacigm007** [comment]
> Can you do `sudo systemctl config nginx` to check if there are no errors in the config. Attach the output of the command. You can read more on https://docs.rackspace.com/support/how-to/basic-nginx-troubleshooting/#:~:text=Through%20a%20simple%20command%20you,line%20where%20the%20problem%20is.

![image](https://user-images.githubusercontent.com/65663517/232241519-9045d356-bff7-463a-b6f9-0bb36ff835bb.png)

**Comment by dclipca** [comment]
> > Can you do `sudo systemctl config nginx` to check if there are no errors in the config. Attach the output of the command. You can read more on https://docs.rackspace.com/support/how-to/basic-nginx-troubleshooting/#:~:text=Through%20a%20simple%20command%20you,line%20where%20the%20problem%20is.
> 
> ![image](https://user-images.githubusercontent.com/65663517/232241519-9045d356-bff7-463a-b6f9-0bb36ff835bb.png)

I think this means that the config is incorrect or something wrong with NGINX. 

Run:
`sudo nginx -t`

as per tutorial and you should get
`
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
`

if not there's something wrong with NGINX.

**Comment by dacigm007** [comment]
> > > Can you do `sudo systemctl config nginx` to check if there are no errors in the config. Attach the output of the command. You can read more on https://docs.rackspace.com/support/how-to/basic-nginx-troubleshooting/#:~:text=Through%20a%20simple%20command%20you,line%20where%20the%20problem%20is.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/65663517/232241519-9045d356-bff7-463a-b6f9-0bb36ff835bb.png)
> 
> I think this means that the config is incorrect or something is wrong with NGINX.
> 
> Run: `sudo nginx -t`
> 
> as per tutorial and you should get `nginx: the configuration file /etc/nginx/nginx.conf syntax is ok nginx: configuration file /etc/nginx/nginx.conf test is successful`
> 
> if not there's something wrong with NGINX.


i just reinstalled everything and i actually run into other issue and that was also issue on first install when i try to create dummy data i get this on pic you can also see that nginx is good 
![image](https://user-images.githubusercontent.com/65663517/232252974-bae4bc6d-ceb0-4078-9af3-81832b6c0f37.png)

**Comment by dclipca** [comment]
@Gralien @botdigit-admin can you take a look guys? not sure what is this.

**Comment by dacigm007** [comment]
> @Gralien @botdigit-admin can you take a look guys? not sure what is this.

sorry for taking your time whole time i was deleting whole .env file instead of modifying just db details, thanks for help, again sorry for taking your time

**Comment by Gralien** [comment]
Script timeout. Times out before crypto transaction complete?

**Comment by dclipca** [comment]
@Gralien thank you for taking the time!

**Comment by Gralien** [comment]
Hi. Yeah. Been busy lately. Still here...!
