### ISSUE TITLE
How Install In Hosting

### ISSUE THREAD

**Issue by TheShadowsHackers** [eckmarcommunity/eckmar#59]

**Comment by dclipca** [comment]
Do you mean how to host it? In a simple sentence, you get an Ubuntu virtual machine as per https://github.com/eckmarcommunity/eckmar/blob/master/INSTALLATION.md and follow instructions.

**Comment by TheShadowsHackers** [comment]
ok, Can you make a complete video of installation, to make it easier to understand without any errors

**Comment by dclipca** [comment]
> ok, Can you make a complete video of installation, to make it easier to understand without any errors.

Sure. I will find some time to make a video in the near future.

**Comment by dclipca** [comment]
Closing because this issue clutters other more important issues.

**Comment by dclipca** [comment]
Closing because this issue clutters other more important issues.
