### ISSUE TITLE
Where can I set the marketplace's own pgp?

### ISSUE THREAD

**Issue by Wizzard234** [eckmarcommunity/eckmar#60]
I tried to add a a new pgp key to a user, and when I need to decrypt the secret message, I can't find the market's own pgp. (Like in the demo under pgp menu)

Can anybody help please?

**Comment by dclipca** [comment]
> I tried to add a a new pgp key to a user, and when I need to decrypt the secret message, I can't find the market's own pgp. (Like in the demo under pgp menu)
> 
> Can anybody help please?

Did you solve this? If yes, please illustrate why other people can see.

**Comment by emmaston1err** [comment]
anyone can help on that ? im searching 2 days
