### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by rahi1990** [eckmarcommunity/eckmar#64]
when i enter "composer install" it gives an error 

the error -

In Filesystem.php line 182:

  /var/www/eckmar/vendor does not exist and could not be created.

**Comment by dclipca** [comment]
@rahi1990 I think I had this before. I think it's related to read/write permissions. Please make sure you followed that part of the tutorial correctly.

**Comment by rahi1990** [comment]
ok i think i fixed it .

you just have to -   sudo chown -R "USER" /var/www/eckmar

here in "USER" you put your username . just type "whoami" to  find "USER''

**Comment by dclipca** [comment]
🚀🚀🚀
