### ISSUE TITLE
composer install issue 

### ISSUE THREAD

**Issue by ameeraz19** [eckmarcommunity/eckmar#71]
i tried so hard to fix it but nothing work for me what could cause this error? (nothing helpful on the internet)

**php -v**
PHP 7.2.34-40+0~20230815.87+debian11~1.gbpe8e12b (cli) (built: Aug 15 2023 09:51:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.34-40+0~20230815.87+debian11~1.gbpe8e12b, Copyright (c) 1999-2018, by Zend Technologies

**composer install**

PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Console\str_contains() in /usr/share/php/Symfony/Component/Console/Application.php:860
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Application.php(840): Symfony\Component\Console\Application->doRenderThrowable(Object(Error), Object(Symfony\Component\Console\Output\StreamOutput))
#1 /usr/share/php/Symfony/Component/Console/Application.php(154): Symfony\Component\Console\Application->renderThrowable(Object(Error), Object(Symfony\Component\Console\Output\StreamOutput))
#2 [internal function]: Symfony\Component\Console\Application->Symfony\Component\Console\{closure}(Object(Error))
#3 {main}
  thrown in /usr/share/php/Symfony/Component/Console/Application.php on line 860

Fatal error: Uncaught Error: Call to undefined function Symfony\Component\Console\str_contains() in /usr/share/php/Symfony/Component/Console/Application.php:860
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Application.php(840): Symfony\Component\Console\Application->doRenderThrowable(Object(Error), Object(Symfony\Component\Console\Output\StreamOutput))
#1 /usr/share/php/Symfony/Component/Console/Application.php(154): Symfony\Component\Console\Application->renderThrowable(Object(Error), Object(Symfony\Component\Console\Output\StreamOutput))
#2 [internal function]: Symfony\Component\Console\Application->Symfony\Component\Console\{closure}(Object(Error))
#3 {main}
  thrown in /usr/share/php/Symfony/Component/Console/Application.php on line 860

**Comment by dclipca** [comment]
Weird error. Start the tutorial (ideally multiple times) so we confirm it's not due to an error in installation.

**Comment by ameeraz19** [comment]
I started over for 5-6 times, always got the same error, I tried on multiply  kali machines and version but nothing helpful...

**Comment by dclipca** [comment]
> I started over for 5-6 times, always got the same error, I tried on multiply kali machines and version but nothing helpful...

Would it be acceptable for your use case to use Ubuntu? The tutorial is presuming that the user is using Ubuntu.

**Comment by ameeraz19** [comment]
> Would it be acceptable for your use case to use Ubuntu? The tutorial is presuming that the user is using Ubuntu.

**yeah thanks my friend just running it on ubuntu fix the error!**

**Comment by dclipca** [comment]
> > Would it be acceptable for your use case to use Ubuntu? The tutorial is presuming that the user is using Ubuntu.
> 
> **yeah thanks my friend just running it on ubuntu fix the error!**

Sounds good. Closing this issue.

**Comment by dclipca** [comment]
Sounds good. Closing this issue.
