### ISSUE TITLE
composer installation error

### ISSUE THREAD

**Issue by landy444** [eckmarcommunity/eckmar#76]
![01](https://github.com/eckmarcommunity/eckmar/assets/145150531/fdef0e4e-1999-4ebf-9c2e-1191e572d029)

**Comment by dclipca** [comment]
@landy444 is this on Ubuntu?

**Comment by landy444** [comment]
yes ubuntu23.04
composer 2.6.2
I upgraded php from 7.2 o 8.2
it was showing error of PHP Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /usr/share/php/Composer/IO/BaseIO.php on line 163

Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /usr/share/php/Composer/IO/BaseIO.php on line 163 
while it was at php7.2.
composer 2.6.2

**Comment by dclipca** [comment]
> yes ubuntu23.04 composer 2.6.2 I upgraded php from 7.2 o 8.2 it was showing error of PHP Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /usr/share/php/Composer/IO/BaseIO.php on line 163
> 
> Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /usr/share/php/Composer/IO/BaseIO.php on line 163 while it was at php7.2. composer 2.6.2

I think upgrading might have been the issue. Can you repeat again without deviating from the guide?

**Comment by landy444** [comment]
after restarting everything from scratch and trying to install from php7.2 composer 2.6.2
![2](https://github.com/eckmarcommunity/eckmar/assets/145150531/f4bc7e6c-9c5a-43cd-acaf-95fc759c04dc)

**Comment by landy444** [comment]
it keeps asking me it can't create folders so I run composer in sudo but still it stops at this point.

![3](https://github.com/eckmarcommunity/eckmar/assets/145150531/a3de9b28-1a2c-45fa-ae61-9a4c245a2bf2)

**Comment by landy444** [comment]
Find line 116 and comment it:

$packages = json_decode($this->files->get($path), true);

Add two new lines after the above commented line:

$installed = json_decode($this->files->get($path), true);
$packages = $installed['packages'] ?? $installed;

**Comment by landy444** [comment]
@dclipca any idea?

**Comment by landy444** [comment]
can you at least try to install in your vm if the guide is correct?

**Comment by landy444** [comment]
![Uploading 4.png…]()

**Comment by landy444** [comment]
![4](https://github.com/eckmarcommunity/eckmar/assets/145150531/f4db6ab7-a9de-47ed-9524-93db83563a05)

**Comment by dclipca** [comment]
> can you at least try to install in your vm if the guide is correct?

I am not am my place right now will try later if I don't get lazy. It should work because other people made it work based on the guide.

**Comment by dclipca** [comment]
Really no idea what's this error is about

**Comment by ffeel31** [comment]
which composer version is ideal for this project?
