### ISSUE TITLE
When entering website URL redirect to login page

### ISSUE THREAD

**Issue by unintends** [eckmarcommunity/eckmar#83]
How can I make that no one could ever see my website but just after signing up or logging in, could you give me a snippet code and how could I implement it and where? Thank you

**Comment by dclipca** [comment]
In your PHP files, at the beginning of each file or within a common included header file, you could have a snippet of code like this:
```php
<?php
session_start();  // Start the session
if (!isset($_SESSION['user_id'])) {  // Check if the user is not logged in
    header('Location: login.php');  // Redirect to the login page
    exit();
}
?>
```

**Comment by dclipca** [comment]
But better with middleware:
```php
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware('auth');
```
This is very general but should point you in the right direction.

**Comment by unintends** [comment]
Could you be more explicit? How could I implement this to the current website code?
