### ISSUE TITLE
Monero node not connecting

### ISSUE THREAD

**Issue by unintends** [eckmarcommunity/eckmar#85]
Hi, I set up the monero node, all of it, I started ./monerod and ./monero-wallet-rpc but when I set up al the details in .env file and try to make a checkout it says 'Error happened!'
What should I do?

**Comment by unintends** [comment]
Could someone help? Maybe @rahi1990 you could know more about this?

**Comment by rahi1990** [comment]
What's the full command you used to start monero rpc wallet ?

**Comment by unintends** [comment]
./monero-wallet-rpc  --wallet-file=defaultfile --prompt-for-password --rpc-bind-port=18089 --rpc-bind-ip=127.0.0.1 --daemon-address=127.0.0.1:18081 --daemon-login=redacted:redacted --confirm-external-bind

This one.

**Comment by rahi1990** [comment]
Rpc login was not working for me so I added  -- disable-rpc-login

**Comment by unintends** [comment]
What about ./monerod starting? I should keep --rpc-login there? So the website can connect to it?

**Comment by rahi1990** [comment]
Start ./monerod  , then on other window start wallet rpc . Both should be running

**Comment by rahi1990** [comment]
Just monerod with just ./monerod

**Comment by unintends** [comment]
And what the port should be on the website 18081 or 18083?

**Comment by rahi1990** [comment]
Monero rpc wallet should be on port 83 and on .env file add port 83

**Comment by unintends** [comment]
so, on 18083?

**Comment by rahi1990** [comment]
Yes

**Comment by rahi1990** [comment]
The market connects with the rpc wallet

**Comment by unintends** [comment]
It's still giving me 'Error happened!' should I reload the website somehow? As my monero firewall allows 18081 & 18083 connection

**Comment by rahi1990** [comment]
Make a new user , is your node fully synced ?

**Comment by unintends** [comment]
Yeah my node is fully synced, so I need to make a new user on the website

**Comment by rahi1990** [comment]
Yes you should try that , buz it's also happened to me

**Comment by unintends** [comment]
Well, i don't know I guess i will try later, cus it still seems that 'Error happened!' error happens..

**Comment by rahi1990** [comment]
Did you set the market address ? On .env ?

**Comment by unintends** [comment]
if you mean the MONERO_HOST yes I did

**Comment by rahi1990** [comment]
Sorry. On coins.php

**Comment by rahi1990** [comment]
In config folder open coins.php

**Comment by unintends** [comment]
Yeah and on the market addresses, I have 2 set

**Comment by rahi1990** [comment]
Yes . Give your wallet public address there

**Comment by unintends** [comment]
public key? or just the address

**Comment by rahi1990** [comment]
Public key or public address same

**Comment by rahi1990** [comment]
On the coin list uncomment xmr , bcuz you are using xmr . Then monero section add host .port etc

**Comment by unintends** [comment]
Yes, I uncommented xmr, I added 2 addresses on market address, configured the section and still the error happens, maybe it's something with the website..

**Comment by rahi1990** [comment]
When you start rpc wallet does it say "starting wallet rpc server " ?

**Comment by unintends** [comment]
Yeah it does, and I don't get any daemon connection error

**Comment by rahi1990** [comment]
Strange

**Comment by unintends** [comment]
Maybe clearing the config cache?

**Comment by rahi1990** [comment]
Try that

**Comment by rahi1990** [comment]
And restar nginx

**Comment by unintends** [comment]
Yeah, still the error happens I don't know what to do now..

**Comment by rahi1990** [comment]
Check all the ports

**Comment by rahi1990** [comment]
Maybe the ports are not right

**Comment by unintends** [comment]
Also, what username & password should be provided on the .env the --daemon-login one?

**Comment by unintends** [comment]
[ 1] 18081                      ALLOW IN    Anywhere
[ 2] 18083                      ALLOW IN    Anywhere
[ 3] 18081 (v6)                 ALLOW IN    Anywhere (v6)
[ 4] 18083 (v6)                 ALLOW IN    Anywhere (v6)

**Comment by rahi1990** [comment]
Did you set the port correctly in .env and coin config.php ?

**Comment by unintends** [comment]
MONERO_PORT=18083 -> this is .env

'port' => intval(env('MONERO_PORT', 18083)) -> config.php

        'xmr' => \App\Marketplace\Payment\MoneroPayment::class, -> also this

**Comment by rahi1990** [comment]
When you click become a vendor, did you see any monero address ?

**Comment by unintends** [comment]
No, but I guess you need to have a small amount of money in the market address to show up, right?

**Comment by rahi1990** [comment]
No actually, you should see a monero address

**Comment by rahi1990** [comment]
Your script and node running on same pc ?

**Comment by unintends** [comment]
No, the monero node is running on another machine same as bitcoin node but the bitcoin node seems to work and I did the same as monero I allowed the ports, let it sync then trying to connect.

**Comment by rahi1990** [comment]
What's your monero host IP ?

**Comment by unintends** [comment]
Should I check with a command if it's online?

**Comment by rahi1990** [comment]
Ok

**Comment by unintends** [comment]
so when I curl and do get_balance it works, but with the website it doesn't :/

**Comment by rahi1990** [comment]
Post the log here

**Comment by unintends** [comment]
Unable to connect to http://65.108.228.155:18083/json_rpc Error: Failed to connect to 65.108.228.155 port 18083: Connection refused

**Comment by unintends** [comment]
Unable to connect to http://xx.xxx.xxx.xxx:18083/json_rpc Error: Failed to connect to 65.108.228.155 port 18083: Connection refused

**Comment by unintends** [comment]
Unable to connect to http://xx.xxx.xxx.xxx:18083/json_rpc Error: Failed to connect to xx.xxx.xxx.xxx port 18083: Connection refused

**Comment by unintends** [comment]
But when testing curl on the machine it works?

**Comment by rahi1990** [comment]
I think something is blocking the port

**Comment by rahi1990** [comment]
Did you open your port on router ?

**Comment by unintends** [comment]
I opened the port 18081, 18083 on UFW because I’m running it on Ubuntu

**Comment by rahi1990** [comment]
Also open port 18080 . Give it a try

**Comment by unintends** [comment]
Open port 18080 and rebind the port from 18083 to 18080? Or keep the same port for the wallet rpc

**Comment by rahi1990** [comment]
Keep the port , just open extra port 18080

**Comment by unintends** [comment]
Still 'Unable to connect to http://xx.xxx.xxx.xxx:18083/json_rpc Error: Failed to connect to xx.xxx.xxx.xxx port 18083: Connection refused'
I don't know any solve, maybe someone will check this out? I don't know

**Comment by rahi1990** [comment]
You opened ports on your router and restarted pc right ?

**Comment by unintends** [comment]
Yes I opened all of the ports & reloaded the UFW

**Comment by rahi1990** [comment]
Not just ufw . You have open ports from router too. Check port forwarding on Google with your router model name

**Comment by unintends** [comment]
Yeah but i'm not using a windows machine, I'm using a dedicated server with Ubuntu though.

**Comment by rahi1990** [comment]
I see

**Comment by rahi1990** [comment]
@Gralien

**Comment by sacommscc** [comment]
if still not fixed i can configure and fix issue you facing but a price

**Comment by unintends** [comment]
Fixed it like 2 days ago, I forgot to close this lol, thanks for help

**Comment by ejinbt** [comment]
how you fixed it?
